/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.asperan.mimeinfo

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.nulls.shouldNotBeNull
import org.gradle.testfixtures.ProjectBuilder

/**
 * A simple unit test for the 'io.github.asperan.mimeinfo.greeting' plugin.
 */
class MimeInfoPluginTest : FunSpec() {
    init {
        test("plugin registers task") {
            // Create a test project and apply the plugin
            val project = ProjectBuilder.builder().build()
            project.plugins.apply("io.github.asperan.mimeinfo-gradle-plugin")

            // Verify the result
            project.tasks.findByName("greeting").shouldNotBeNull()
        }
    }
}
